# Schedule

The list of topics is tentative and the pacing subject to change. Assigned readings are listed below the table for each unit.

| **Week** | **Date** | **Topic** | **Due** |
|---|---|---|---|
| 1 | Tue, Mar 29 | [Welcome to the course](https://uc-dataviz-slides.netlify.app/01-intro/) |  |
|  | Thu, Mar 31 | [Grammar of graphics](https://uc-dataviz-slides.netlify.app/02-grammar-of-graphics/) | Survey: [Collecting GitHub usernames](https://forms.gle/HkaVKm7wgUPRW1Zh7)  |
| 2 | Tue, Apr 5 | [Looking at data](https://uc-dataviz-slides.netlify.app/03-look-at-data/) |  |
|  | Thu, Apr 7 | [Deep dive: geoms](https://uc-dataviz-slides.netlify.app/04-geoms/) |  |
| 3 | Tue, Apr 12 | [Deep dive: stats + scales + guides](https://uc-dataviz-slides.netlify.app/05-stats-scales-guides/) | HW1 |
|  | Thu, Apr 14 | [Deep dive: coordinate systems + faceting](https://uc-dataviz-slides.netlify.app/06-coordinates-facets/) |  |
| 4 | Tue, Apr 19 | [Optimizing color spaces](https://uc-dataviz-slides.netlify.app/07-optimizing-color-spaces/) | HW2 |
|  | Thu, Apr 21 | Deep dive: themes + axes + annotation |  |
| 5 | Tue, Apr 26 | Presentation ready plots |  |
|  | Thu, Apr 28 | Project 1 presentations |  |
| 6 | Tue, May 3 | Visualizing geospatial data I |  |
|  | Thu, May 5 | Visualizing geospatial data II |  |
| 7 | Tue, May 10 | Visualizing time series data | HW3 |
|  | Thu, May 12 | Visualizing text and network data?/Animation |  |
| 8 | Tue, May 17 | Interactive reporting | HW4 |
|  | Thu, May 19 | Interactive visualization |  |
| 9 | Tue, May 24 | Tables |  |
|  | Thu, May 26 | Accessibility |  |
| Exam | TBD | Project 2 presentations |  |

## Welcome to the course 

##### Required {.unnumbered}

- *The Truthful Art* by Alberto Cairo, chapter 2 (on electronic course reserve in Canvas)

##### Recommended {.unnumbered}


## Grammar of graphics 

- Wickham et. al., [chapter 13](https://ggplot2-book.org/mastery.html)

## Looking at data 

##### Required {.unnumbered}

- [Healy, chapter 1](https://socviz.co/lookatdata.html)
- [Study: Charts change hearts and minds better than words do](https://www.washingtonpost.com/news/wonk/wp/2018/06/15/study-charts-change-hearts-and-minds-better-than-words-do/)

##### Recommended {.unnumbered}

- Wilke [chapter 2](https://clauswilke.com/dataviz/aesthetic-mapping.html)

## Deep dive: geoms 

##### Required {.unnumbered}

- Wickham et. al., [chapter 14](https://ggplot2-book.org/layers.html)

##### Recommended {.unnumbered}

## Deep dive: stats + scales + guides 

##### Required {.unnumbered}

- Wickham et. al., [chapter 15](https://ggplot2-book.org/scales-guides.html)

##### Recommended {.unnumbered}

## Deep dive: coordinate systems + faceting 

##### Required {.unnumbered}

- Wickham et. al., [chapter 16](https://ggplot2-book.org/coord.html) + [chapter 17](https://ggplot2-book.org/facet.html)

##### Recommended {.unnumbered}

## Optimizing color spaces

##### Required {.unnumbered}

- Wilke [chapter 4](https://clauswilke.com/dataviz/color-basics.html) + [chapter 19](https://clauswilke.com/dataviz/color-pitfalls.html)

##### Recommended {.unnumbered}

- [How to create an organizational color palette](https://blog.datawrapper.de/colors-for-data-vis-style-guides/)
- [Any blog posts by Lisa Charlotte Muth](https://blog.datawrapper.de/category/color-in-data-vis/) - excellent series of posts on using color in data visualization. None of the posts have direct examples in R but provide a detailed overview of considerations in selecting color palettes.

## Deep dive: themes + axes + annotation 

##### Required {.unnumbered}

- Wickham et. al., [chapter 18](https://ggplot2-book.org/polishing.html) + [chapter 8](https://ggplot2-book.org/annotations.html)

##### Recommended {.unnumbered}

## Presentation ready plots 

##### Required {.unnumbered}

- Wilke [chapter 29](https://clauswilke.com/dataviz/telling-a-story.html)
- Healy [chapter 8](https://socviz.co/refineplots.html)

##### Recommended {.unnumbered}


## Project 1 presentations 


## Visualizing geospatial data I 

##### Required {.unnumbered}

- Wilke [chapter 15](https://clauswilke.com/dataviz/geospatial-data.html)

##### Recommended {.unnumbered}

## Visualizing geospatial data II 

##### Required {.unnumbered}


##### Recommended {.unnumbered}

## Visualizing time series data 

##### Required {.unnumbered}

- Wilke [chapter 13](https://clauswilke.com/dataviz/time-series.html) + [chapter 14](https://clauswilke.com/dataviz/visualizing-trends.html)

##### Recommended {.unnumbered}

## Visualizing text and network data?/Animation 

##### Required {.unnumbered}

- Wickham et. al., [chapter 7](https://ggplot2-book.org/networks.html)

##### Recommended {.unnumbered}

## Interactive reporting

##### Required {.unnumbered}

- Wickham [chapter 1](https://mastering-shiny.org/basic-app.html) + [chapter 2](https://mastering-shiny.org/basic-ui.html)

##### Recommended {.unnumbered}

## Interactive visualization

##### Required {.unnumbered}

- Wickham [chapter 3](https://mastering-shiny.org/basic-reactivity.html) + [chapter 7](https://mastering-shiny.org/action-graphics.html)

##### Recommended {.unnumbered}

## Tables 

##### Required {.unnumbered}

- Paper: [Jon Schwabish - Ten Guidelines for Better Tables](https://www-cambridge-org.proxy.uchicago.edu/core/journals/journal-of-benefit-cost-analysis/article/ten-guidelines-for-better-tables/74C6FD9FEB12038A52A95B9FBCA05A12)
- Blog post: [Tom Mock - 10+ Guidelines for Better Tables in R](https://themockup.blog/posts/2020-09-04-10-table-rules-in-r/)

##### Recommended {.unnumbered}

## Accessibility 

##### Required {.unnumbered}

- [Amy Cesal - Writing Alt Text for Data Visualization](https://medium.com/nightingale/writing-alt-text-for-data-visualization-2a218ef43f81)

##### Recommended {.unnumbered}




